### ISSUE TITLE
XPCOMGlueLoad error

### ISSUE THREAD

**Issue by tmescic** [ernw/insinuator-snippets#1]
I am getting this when i run your script (Ubuntu 14.10 64 bit):

XPCOMGlueLoad error for file /opt/webex/firefox_x86/libxul.so:
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

Any ideas?

**Comment by 0xb35c** [comment]
I never saw this error before, but it looks like the file is not existing. Did you do [step 4](https://github.com/ernw/insinuator-snippets/tree/master/webex-linux) and changed the paths in the script to the place you extracted the zip-files? It's line 4 and 5 in the script.

**Comment by tmescic** [comment]
Yep. Did everything correctly. After some googling, I've discovered it's an issue with running 32-bit firefox on 64-bit Linux.

**Comment by 0xb35c** [comment]
Ok, can you maybe share the link? Thank you.

**Comment by bluec0re** [comment]
You could maybe try to install firefox x86 via apt by enabling the 32bit repositories:

http://www.unixmen.com/enable-32-bit-support-64-bit-ubuntu-13-10-greater/

**Comment by tmescic** [comment]
Ok, tnx for that. Firefox now works (installed with: sudo apt-get install firefox:i385). However, webex still not working using the script. When I go to the WebEx test page, the browser freezes and I get this command line output: 
VMLauncher.afterStart(): starting JVM process watcher
java.lang.InterruptedException
    at java.lang.Object.wait(Native Method)
    at sun.plugin2.message.Queue.waitForMessage(Unknown Source)
    at sun.plugin2.message.Pipe$1.run(Unknown Source)
    at com.sun.deploy.util.Waiter$1.wait(Unknown Source)
    at com.sun.deploy.util.Waiter.runAndWait(Unknown Source)
    at sun.plugin2.message.Pipe.receive(Unknown Source)
    at sun.plugin2.main.server.JVMInstance$WorkerThread.run(Unknown Source)

**Comment by 0xb35c** [comment]
Sorry, I can't help you with the error. But essentially you could also try to install the i386 version of the jre (similar commend like above), then it should work out-of-the-box without the script.

Also out of curiosity: Did you ever check if the file from the first error message (/opt/webex/firefox_x86/libxul.so) really did exist, or not? And also if it has correct permissions?

**Comment by tmescic** [comment]
Yes, the file existed and the permission were correct. Apparently, the error is caused by missing 32 bit libs (see: https://bugzilla.mozilla.org/show_bug.cgi?id=704298).

Installing 32-bit Firefox and 32-bit JRE was exactly what I was trying to avoid with this script :)

**Comment by 0xb35c** [comment]
I took a look at my installed packages. It may be that you have to install those:

```
libdbus-1-3:i386
libdbus-glib-1-2:i386
```

At least it seems, that Firefox is looking for them.
